name: CI
# triggered on pushes
on:
  push:
    branches:
    - develop
    - actions

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix: 
        destination: ['Phone SE', 'iPhone 11 Pro']
        xcode: ['/Applications/Xcode_11.4.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'test_app'
        env:
          destination: $
          SCHEME: 'CalculatorByFr3qFly'
      - name: Uploading Failed Tests
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: test_output
          path: ./fastlane/test_output
      
