name: Upload build    
on:
  push:
    branches:
    - master

jobs: 
  deploy:
    name: Deploy
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Upload
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'beta'
        env:
          SCHEME: 'CalculatorByFr3qFly'
          CODE_SIGNING: ${{ secrets.CODE_SIGNING }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          
      - name: Bump Build Number
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'bump'
        env: 
          PROJECT_NAME: 'CalculatorByFr3qFly'
          COMMIT_TAG: 'AUTO'